name: Vault OIDC Test

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  vault-oidc-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write Vault CA cert to file
        run: |
          echo "$VAULT_CA" > vault-ca.pem
        env:
          VAULT_CA: ${{ secrets.VAULT_CA }}

      - name: Test curl with direct CA cert path
        run: |
          curl --cacert ${{ github.workspace }}/vault-ca.pem https://vault-cluster-plus-public-vault-1e26e30b.d93627cf.z1.hashicorp.cloud:8200/v1/sys/health | jq

      - name: Read secret from Vault
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: https://vault-cluster-plus-public-vault-1e26e30b.d93627cf.z1.hashicorp.cloud:8200
          caCertificate: $VAULT_CA
          namespace: admin
          method: jwt
          role: myproject-production
          secrets: |
            kv/data/production/app username | APP_SECRET

      - name: Output things
        run: |
          echo APP Secret: ${{ env.APP_SECRET }}  | sed 's/./& /g'

      - name: Revoke token
        run: |
          curl -X POST -sv -H "X-Vault-Token: ${{ env.VAULT_TOKEN }}" https://vault-cluster-plus-public-vault-1e26e30b.d93627cf.z1.hashicorp.cloud:8200/v1/auth/token/revoke-self
