name: Vault OIDC Test

on:
  workflow_dispatch:

jobs:
  vault-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read secret from Vault
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: https://vault-cluster-dev-1304-public-vault-25036c28.52fe4c32.local.hcp.dev:8200
          method: jwt
          path: jwt
          role: myproject-production
          secrets: |
            secret/data/production/app username | VAULT_USERNAME ;
            secret/data/production/app password | VAULT_PASSWORD
      - name: Dump OIDC Token Claims
        run: |
          echo "${ACTIONS_ID_TOKEN}" | cut -d '.' -f2 | base64 -d | jq
        env:
          ACTIONS_ID_TOKEN: ${{ steps.get-token.outputs.token }}
        id: get-token
