name: Vault OIDC Test

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  vault-oidc-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write Vault CA cert to file
        run: |
          echo "$VAULT_CA" > vault-ca.pem
        env:
          VAULT_CA: ${{ secrets.VAULT_CA }}

      - name: Debug cert
        run: |
          ls -l vault-ca.pem
          cat vault-ca.pem
      
      - name: Test curl with CA cert
        run: |
          curl --cacert vault-ca.pem https://vault-cluster-plus-public-vault-1e26e30b.d93627cf.z1.hashicorp.cloud:8200/v1/sys/health | jq
      
      - name: Test curl with direct CA cert path
        run: |
          curl --cacert ${{ github.workspace }}/vault-ca.pem https://vault-cluster-plus-public-vault-1e26e30b.d93627cf.z1.hashicorp.cloud:8200/v1/sys/health | jq


      - name: Read secret from Vault
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: https://vault-cluster-plus-public-vault-1e26e30b.d93627cf.z1.hashicorp.cloud:8200
          namespace: admin
          method: jwt
          role: myproject-production
          secrets: |
            kv/data/production/app username | VAULT_USERNAME ;
            kv/data/production/app password | VAULT_PASSWORD
        env:
          VAULT_CACERT: ${{ github.workspace }}/vault-ca.pem
